Check to see if Tag is in releases

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -7,7 +7,6 @@ on:
       tags:
         description: 'Release Tag'
         required: true
-        default: 'master'
 
 env:
   DOCKERHUB_REPOSITORY:     dfedigital/get-into-teaching-api
@@ -24,6 +23,16 @@ jobs:
         shell: bash
 
     steps:
+
+       - name: Check Tag is a Release
+         run: |
+               rval=$(curl -s -X GET https://api.github.com/repos/DFE-Digital/get-into-teaching-content/releases/tags/${{ github.event.inputs.tags }} | jq -r ".message")
+               if [ "${rval}" = "Not Found" ]
+               then
+                   echo "Tag ${{ github.event.inputs.tags }} cannot be found in releases"
+                   exit 1
+               fi
+               exit 0
 
        - name: Checkout
          uses: actions/checkout@v2
@@ -80,37 +89,37 @@ jobs:
              TF_VAR_SENTRY_URL:        "${{ secrets.SENTRY_URL }}"
 
                 
-       - name: Terraform Apply
-         run: |
-             cd terraform/paas && pwd
-             terraform apply -auto-approve plan
-         env:
-             ARM_ACCESS_KEY:           "${{ secrets.PROD_ARM_ACCESS_KEY  }}"
-             TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME   }}"
-             TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD   }}"
-   
-       - name:  Smoke Test
-         run: |
-             tests/confidence/healthcheck.sh "get-into-teaching-api-prod"  "${{ steps.sha.outputs.short}}" 
- 
-       - name: Create Sentry release
-         if: success()
-         uses: getsentry/action-release@v1.0.0
-         env:
-           SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
-           SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
-           SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
-         with:
-           environment: production
- 
-       - name: Slack Notification
-         if: failure()
-         uses: rtCamp/action-slack-notify@master
-         env:
-           SLACK_CHANNEL: getintoteaching_tech
-           SLACK_COLOR: '#3278BD'
-           SLACK_ICON: https://github.com/rtCamp.png?size=48
-           SLACK_MESSAGE: ':disappointed_relieved: Pipeline Failure carrying out job ${{github.job}} :disappointed_relieved:'
-           SLACK_TITLE: 'Failure: ${{ github.workflow }}'
-           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
+#      - name: Terraform Apply
+#        run: |
+#            cd terraform/paas && pwd
+#            terraform apply -auto-approve plan
+#        env:
+#            ARM_ACCESS_KEY:           "${{ secrets.PROD_ARM_ACCESS_KEY  }}"
+#            TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME   }}"
+#            TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD   }}"
+#  
+#      - name:  Smoke Test
+#        run: |
+#            tests/confidence/healthcheck.sh "get-into-teaching-api-prod"  "${{ steps.sha.outputs.short}}" 
+#
+#      - name: Create Sentry release
+#        if: success()
+#        uses: getsentry/action-release@v1.0.0
+#        env:
+#          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
+#          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
+#          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
+#        with:
+#          environment: production
+#
+#      - name: Slack Notification
+#        if: failure()
+#        uses: rtCamp/action-slack-notify@master
+#        env:
+#          SLACK_CHANNEL: getintoteaching_tech
+#          SLACK_COLOR: '#3278BD'
+#          SLACK_ICON: https://github.com/rtCamp.png?size=48
+#          SLACK_MESSAGE: ':disappointed_relieved: Pipeline Failure carrying out job ${{github.job}} :disappointed_relieved:'
+#          SLACK_TITLE: 'Failure: ${{ github.workflow }}'
+#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
 
